[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
monitor_port = rfc2217://localhost:4000

lib_deps =
    miguelbalboa/MFRC522@^1.4.10
