#ifndef SECRETS_EXAMPLE_H
#define SECRETS_EXAMPLE_H

#define SECRET_SSID "Wokwi-GUEST"
#define SECRET_PASS ""


#define SECRET_MQTT_SERVER "host.wokwi.internal"
#define SECRET_MQTT_PORT 1883


#define SECRET_MQTT_CLIENT_ID "ESP32_IOT-A6F8B4147B"
#define SECRET_MQTT_USERNAME ""
#define SECRET_MQTT_PASSWORD ""

#endif // SECRETS_EXAMPLE_H
